/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package IHM;

import Ecouteurs.EcouteurRecherche;
import java.awt.Component;
import java.awt.PopupMenu;
import javax.swing.DefaultListModel;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;

import recuperationtraces.*;

/**
 *
 * @author Tigro
 */
public class AjouterIndicateur extends javax.swing.JPanel {
      DefaultListModel dlm2;
      DefaultListModel dlm1;
      Racine r;
    /**
     * Creates new form AjouterIndicateur
     */
    
    List<String> lstAcalculer; 
    public AjouterIndicateur(Racine r) {
        initComponents();
        this.r=r;
        dlm1= new DefaultListModel();
        lstAcalculer=new ArrayList<>();
        JListAllIndicateurs.setModel(dlm1);
        //List<String> lst=new ArrayList<>();
        for (String key : r.getTracesEtIndicateursCalcules().getTr().keySet()){

            dlm1.addElement(key);
        }
        dlm2= new DefaultListModel();
        JListIndicateurUtilise.setModel(dlm2);
        EcouteurRecherche EcoutRech= new EcouteurRecherche(r, this,"Indicateur");
        textRecherche.addKeyListener(EcoutRech);
    }

    public JList getJListAllIndicateurs() {
        return JListAllIndicateurs;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        JListIndicateurUtilise = new javax.swing.JList();
        jScrollPane1 = new javax.swing.JScrollPane();
        JListAllIndicateurs = new javax.swing.JList();
        textRecherche = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        TxtNomNewIndicateur = new javax.swing.JTextField();
        CalculSomme = new javax.swing.JButton();
        CalculMoyenne = new javax.swing.JButton();
        CalculMEcart = new javax.swing.JButton();
        nomIndicateur = new javax.swing.JLabel();
        Recherche = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jButton4.setText("jButton4");

        jTextField3.setText("jTextField3");

        jScrollPane2.setViewportView(JListIndicateurUtilise);

        jScrollPane1.setViewportView(JListAllIndicateurs);

        jButton1.setText(">");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("<");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        CalculSomme.setText("Sommme");
        CalculSomme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculSommeActionPerformed(evt);
            }
        });

        CalculMoyenne.setText("Moyenne");
        CalculMoyenne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculMoyenneActionPerformed(evt);
            }
        });

        CalculMEcart.setText("Ecart");
        CalculMEcart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculMEcartActionPerformed(evt);
            }
        });

        nomIndicateur.setText("Nom du nouvel indicateur  :");

        Recherche.setText("Recherche");
        Recherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RechercheActionPerformed(evt);
            }
        });

        jLabel1.setText("Calcul à éffectuer sur les indicateurs ci-dessus");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Recherche)
                        .addGap(81, 81, 81)
                        .addComponent(textRecherche))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2)
                        .addGap(19, 19, 19))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nomIndicateur, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(TxtNomNewIndicateur, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CalculMoyenne)
                .addGap(50, 50, 50)
                .addComponent(CalculSomme)
                .addGap(50, 50, 50)
                .addComponent(CalculMEcart, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane1))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jButton1)
                        .addGap(32, 32, 32)
                        .addComponent(jButton2)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Recherche)
                            .addComponent(textRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nomIndicateur)
                            .addComponent(TxtNomNewIndicateur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CalculMoyenne)
                    .addComponent(CalculSomme)
                    .addComponent(CalculMEcart))
                .addContainerGap(31, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        //si l'utilisateur a sélectionné une valeur
        if(!JListAllIndicateurs.isSelectionEmpty()){
            //on le change de liste
            System.out.println(lstAcalculer);
            lstAcalculer.add(JListAllIndicateurs.getSelectedValue().toString());
            dlm2.addElement(JListAllIndicateurs.getSelectedValue());
            ((DefaultListModel)JListAllIndicateurs.getModel()).removeElement(JListAllIndicateurs.getSelectedValue());
            System.out.println(lstAcalculer);
            validate();
        }else {
            JOptionPane.showMessageDialog(this, "Veuillez selectionner un element !");
        }
         
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void RechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RechercheActionPerformed
        
        String s= textRecherche.getText(); //la chaine à rechercher
        String[] l=r.getTracesEtIndicateursCalcules().getTr().keySet().toArray(new String[r.getTracesEtIndicateursCalcules().getTr().keySet().size()]);
        DefaultListModel dLM=new DefaultListModel();            
        for(String key:l)
            if(key.contains(s))
                dLM.addElement(key);
        JListAllIndicateurs.setModel(dLM);
        
                
// TODO add your handling code here:
    }//GEN-LAST:event_RechercheActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //si l'utilisateur a sélectionné une valeur
        if(!JListIndicateurUtilise.isSelectionEmpty()){
            //on la change de liste
            lstAcalculer.remove(JListIndicateurUtilise.getSelectedValue().toString());
            ((DefaultListModel)JListAllIndicateurs.getModel()).addElement(JListIndicateurUtilise.getSelectedValue());
            dlm2.removeElement(JListIndicateurUtilise.getSelectedValue());
            System.out.println(lstAcalculer);
            validate();}
        else JOptionPane.showMessageDialog(this, "Veuillez selectionner un element !");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void CalculMoyenneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculMoyenneActionPerformed
        if(!lstAcalculer.isEmpty())
        r.getTracesEtIndicateursCalcules().creerIndicateurMoyenne(TxtNomNewIndicateur.getText(), lstAcalculer);
        else JOptionPane.showMessageDialog(null,"choisissez les indicateurs pour le calcul de la moyenne");
// TODO add your handling code here:
    }//GEN-LAST:event_CalculMoyenneActionPerformed

    private void CalculSommeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculSommeActionPerformed

        if(!lstAcalculer.isEmpty())
        r.getTracesEtIndicateursCalcules().creerIndicateurMoyenne(TxtNomNewIndicateur.getText(), lstAcalculer);
        else JOptionPane.showMessageDialog(null,"choisissez les indicateurs pour le calcul de la somme"); 
        // TODO add your handling code here:
    }//GEN-LAST:event_CalculSommeActionPerformed

    private void CalculMEcartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculMEcartActionPerformed

        if(!lstAcalculer.isEmpty())
        r.getTracesEtIndicateursCalcules().creerIndicateurMoyenne(TxtNomNewIndicateur.getText(), lstAcalculer);
        else JOptionPane.showMessageDialog(null,"choisissez les indicateurs pour le calcule de l'écart");        // TODO add your handling code here:
    }//GEN-LAST:event_CalculMEcartActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CalculMEcart;
    private javax.swing.JButton CalculMoyenne;
    private javax.swing.JButton CalculSomme;
    private javax.swing.JList JListAllIndicateurs;
    private javax.swing.JList JListIndicateurUtilise;
    private javax.swing.JButton Recherche;
    private javax.swing.JTextField TxtNomNewIndicateur;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel nomIndicateur;
    private javax.swing.JTextField textRecherche;
    // End of variables declaration//GEN-END:variables
}
