/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package IHM;

import Ecouteurs.EcouteurRecherche;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import recuperationtraces.*;

/**
 *
 * @author Tigro
 */
public class SupprimerIndicateur extends javax.swing.JPanel {
    DefaultListModel dlm1;
    /**
     * Creates new form SupprimerGroupe
     */
    Racine r;
    public SupprimerIndicateur(Racine r) {
        initComponents();
        this.r=r;
        dlm1= new DefaultListModel();
        JListAllIndicateurs.setModel(dlm1);
        //List<String> lst=new ArrayList<>();
        for (String key : r.getTracesEtIndicateursCalcules().getTr().keySet()){
            dlm1.addElement(key);
        }
        EcouteurRecherche EcoutRech= new EcouteurRecherche(r, this,"SupprimerInd");
        textRecherche.addKeyListener(EcoutRech);
    }

    public JList getJListAllIndicateurs() {
        return JListAllIndicateurs;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        JListAllIndicateurs = new javax.swing.JList();
        BoutonRecherche = new javax.swing.JButton();
        textRecherche = new javax.swing.JTextField();
        BoutonSupprimer = new javax.swing.JButton();

        jScrollPane1.setViewportView(JListAllIndicateurs);

        BoutonRecherche.setText("Recherche");
        BoutonRecherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonRechercheActionPerformed(evt);
            }
        });

        BoutonSupprimer.setText("Supprimer l'indicateur");
        BoutonSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonSupprimerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(BoutonSupprimer)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(28, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(BoutonRecherche)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BoutonRecherche)
                    .addComponent(textRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(BoutonSupprimer)
                .addGap(36, 36, 36))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BoutonRechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonRechercheActionPerformed

        String s= textRecherche.getText(); //la chaine à rechercher
        String[] l=r.getGroupe().keySet().toArray(new String[r.getGroupe().keySet().size()]);
        DefaultListModel dLM=new DefaultListModel();
        for(String key:l)
        if(key.contains(s))
        dLM.addElement(key);
        JListAllIndicateurs.setModel(dLM);

        // TODO add your handling code here:
    }//GEN-LAST:event_BoutonRechercheActionPerformed

    private void BoutonSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonSupprimerActionPerformed
        if(!JListAllIndicateurs.isSelectionEmpty()){
            if (JOptionPane.showConfirmDialog(null,"Êtes vous sur de vouloir supprimer l'indicateur "+JListAllIndicateurs.getSelectedValue().toString()+" ?","Supprimer Indicateur",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
                r.getTracesEtIndicateursCalcules().getTr().remove(JListAllIndicateurs.getSelectedValue().toString());
            }
        }else {
            JOptionPane.showMessageDialog(this, "Veuillez selectionner un element !");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_BoutonSupprimerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BoutonRecherche;
    private javax.swing.JButton BoutonSupprimer;
    private javax.swing.JList JListAllIndicateurs;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField textRecherche;
    // End of variables declaration//GEN-END:variables
}
